### ISSUE TITLE
关于2.7.0即将对ME输出仓、ME输出总线的修改

### ISSUE THREAD

**Issue by Handsonzyx** [ElytraServers/gtnh-no-nerf#13]
### Your requirement

2.7.0将把ME输出仓室的存储容量与放入其中的ME盘挂钩，希望能把这个修改回滚（我的外置奇点容器啊，悲）

### Extra information

https://github.com/GTNewHorizons/GT5-Unofficial/pull/2718

**Comment by Taskeren** [comment]
还没玩过270，过几天看看吧 :3
